apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: genai-backend
  labels:
    app: genai-user-mgmt
    tier: backend
type: Opaque
stringData:
  MONGODB_URL: mongodb://mongo-service.genai-backend.svc.cluster.local:27017
  GROQ_API_KEY: replace-with-real-key

